### ISSUE TITLE
Can't decide where to put the sensor template

### ISSUE THREAD

**Issue by DanielOrneling** [davidrustingha/F1-Calendar-Card#1]
How do I get the sensors needed to populate the card? I saw the yaml file on Github, but I couldn´t get it working anywhere. Whar should I do with this file?

**Comment by iron-LAN** [comment]
Hi Daniel,

It depends on how you're formatting your configuration.

I have everything in include statements so I have a file in a folder so that's one way (check 'splitting the configuration' in the docs).

You would insert them like you normally would, so directly in the config would look like this:

```
template:
  - sensor:
      - name: ....
```

**Comment by iron-LAN** [comment]
I highly recommend splitting the configuration for a good overview of the automations, scripts, scenes etc

**Comment by HA-Peet** [comment]
As soon as FP1 has been done, date and time changes to the next race. So COTA race is on the 24th of october, but FP1 is dated november 5th. Have all dates and times changed when race is done

**Comment by iron-LAN** [comment]
> As soon as FP1 has been done, date and time changes to the next race. So COTA race is on the 24th of october, but FP1 is dated november 5th. Have all dates and times changed when race is done

I've changed the code so after FP2 finishing it will say 'No 2nd practice this week'. Until the next week that does have a 2nd practice. This happens for all events that are visible in the card. So if you have the updated code it should say that there are no events this week.
