### ISSUE TITLE
template sensor 

### ISSUE THREAD

**Issue by jay1972** [davidrustingha/F1-Calendar-Card#2]
the template sensor seems to be causing issues when add to the yaml file. i think some code is either missing or not clear or possibly formatted incorrectly

**Comment by jay1972** [comment]
managed to get the F1 sprint working, but the issue is the format of how the code has been pasted of the template sensor, im having to move loads of code to the correct space to get one of the sensors working

**Comment by iron-LAN** [comment]
As mentioned in the Facebook post:

The code is pasted as working file for those who use include statements to break up the configuration. If you want to implement this directly inside the configuration.yaml file you need to indent the code an extra 4 spaces or 2 tabs.

I'll add this to the readme!

**Comment by jay1972** [comment]
as you know, we got t working. Whats new in the updated senor code

**Comment by iron-LAN** [comment]
The newest version has an update for events that are not 'this' week. So, if the 1st practice is over it would show the date of the next practice, but now it shows 'No 1st free practice this week'. I'm working on showing it a different state like '1st practice is over' or something.

Any ideas on this?
