### ISSUE TITLE
Unable to get sensor working - using merged folder for sensors - Gives no error in Config

### ISSUE THREAD

**Issue by Tomcatter31** [davidrustingha/F1-Calendar-Card#3]
Unable to get sensor working - using merged folder for sensors - Gives no error in Config
![image](https://user-images.githubusercontent.com/57972309/138384446-37d6f054-e5aa-43b0-b814-d62933c808ab.png)

`template:
  - sensor:
    - name: Formula 1
      state: "{{ as_timestamp(strptime(state_attr('calendar.f1_race', 'start_time'), '%d %h %m')) | timestamp_custom('%W')| float == (now().isocalendar()[1]) }}"
      attributes:
        currently_racing: >
          {% if is_state('calendar.f1_fp1', 'on') or is_state('calendar.f1_fp2', 'on') or is_state('calendar.f1_fp3', 'on') or is_state('calendar.f1_qualification', 'on') or is_state('calendar.f1_sprint_race', 'on') or is_state('calendar.f1_sprint_qualifying', 'on') %}
            racing
          {% else %}
            not racing
          {% endif %}
        fp1_day: >
          {% if state_attr('calendar.f1_fp1', 'start_time') == None %}
            No 1st free practice this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_fp1', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} 
          {% endif %}
        fp1_time: >
          {% if state_attr('calendar.f1_fp1', 'start_time') == None %}
            No 1st free practice this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_fp1', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} 
          {% endif %}
        fp2_day: >
          {% if state_attr('calendar.f1_fp2', 'start_time') == None %}
            No 2nd free practice this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_fp2', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} 
          {% endif %}
        fp2_time: >
          {% if state_attr('calendar.f1_fp2', 'start_time') == None %}
            No 2nd free practice this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_fp2', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} 
          {% endif %}
        fp3_day: >
          {% if state_attr('calendar.f1_fp3', 'start_time') == None %}
            No 3rd free practice this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_fp3', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december")  }} 
          {% endif %}
        fp3_time: >
          {% if state_attr('calendar.f1_fp3', 'start_time') == None %}
            No 3rd free practice this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_fp3', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} 
          {% endif %}
        sprint_race_day: >
          {% if state_attr('calendar.f1_sprint_race', 'start_time') == None %}
            No sprint race this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_sprint_race', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december")  }} 
          {% endif %}
        sprint_race_time: >
          {% if state_attr('calendar.f1_sprint_race', 'start_time') == None %}
            No sprint race this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_sprint_race', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} 
          {% endif %}
        sprint_q_day: >
          {% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == None %}
            No sprint qualification this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_sprint_qualifying', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december")  }} 
          {% endif %}
        sprint_q_time: >
          {% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == None %}
            No sprint qualification this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_sprint_qualifying', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} 
          {% endif %}
        q_day: >
          {% if state_attr('calendar.f1_qualification', 'start_time') == None %}
            No qualification this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_qualification', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} 
          {% endif %}
        q_time: >
          {% if state_attr('calendar.f1_qualification', 'start_time') == None %}
            No qualification this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_qualification', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} 
          {% endif %}
        r_day: >
          {% if state_attr('calendar.f1_race', 'start_time') == None %}
            No race this week
          {% elif 'sprint' in state_attr('calendar.f1_race', 'message') %}
            No race this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_race', 'start_time'), '%d %h %m')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} 
          {% endif %}
        r_time: >
          {% if state_attr('calendar.f1_race', 'start_time') == None %}
            No race this week
          {% elif 'sprint' in state_attr('calendar.f1_race', 'message') %}
            No race this week
          {% else %}
            {{ as_timestamp(strptime(state_attr('calendar.f1_race', 'start_time'), '%d %h %m')) | timestamp_custom('%H:%M') }} 
          {% endif %}
        track: >
          {% if state_attr('calendar.f1_race', 'location') == None %}
            No race track this week
          {% else %}
            {{ state_attr('calendar.f1_race', 'location') }}
          {% endif %}
        gp_name: >
          {% if state_attr('calendar.f1_race', 'message') == None %}
            No GP this weekend
          {% else %}
            {{ state_attr('calendar.f1_race', 'message') |replace ('Race: ','') |replace ('2020 ','') |replace ('2021 ','') |replace ('2022 ','') }}
          {% endif %}
    - name: F1 (sprint)
      icon: mdi:keyboard-f1
      state: >
        {% if (as_timestamp(strptime(state_attr('calendar.f1_sprint_race', 'start_time'), '%d %h %m')) | timestamp_custom('%W')| float) == (now().isocalendar()[1]) %}
          on
        {% else %}
          off
        {% endif %}`

![image](https://user-images.githubusercontent.com/57972309/138384592-cf86c2e7-78d9-4d10-ad40-a7e0caec7acb.png)

![image](https://user-images.githubusercontent.com/57972309/138384691-30e63db0-7e46-4f95-815c-adb7cdd0027f.png)

![image](https://user-images.githubusercontent.com/57972309/138384713-c661dd5f-c4d9-4d37-b1bf-2604c49070d1.png)

**Comment by iron-LAN** [comment]
I think the formatting is off, but since Home Assistant technically can't see the sensors it won't show any errors. How did you include the template sensor file/folder in your configuration.yaml?

**Comment by Tomcatter31** [comment]
![image](https://user-images.githubusercontent.com/57972309/138558610-d734e31d-373b-490f-a3ca-b538647f6952.png)

![image](https://user-images.githubusercontent.com/57972309/138558679-d7f93252-7a4e-4681-a809-54cdf13578eb.png)

The other sensors in the folder are working:

![image](https://user-images.githubusercontent.com/57972309/138558717-c9dd34fd-8491-4683-bd99-ed56a8269fc7.png)

**Comment by iron-LAN** [comment]
This is a template sensor, it has to be included under

```
Template:
  - sensor: [include]
```

**Comment by Tomcatter31** [comment]
> This is a template sensor, it has to be included under
> 
> ```
> Template:
>   - sensor: [include]
> ```

Tried that still didnt work, all my other sensors are working fine.

Example:

![image](https://user-images.githubusercontent.com/57972309/138595974-e3ef8a4b-99f9-4619-b1a3-b6ca56adc375.png)
![image](https://user-images.githubusercontent.com/57972309/138595994-d66bdb31-4bbf-44f7-a382-f0ba996ccaa3.png)

![image](https://user-images.githubusercontent.com/57972309/138596025-8cc72ba3-91ed-4886-91ab-3f8ddf09411b.png)

**Comment by iron-LAN** [comment]
You can copy paste the code under the Ari filter entry. If you make sure the indentation is correct it will work.
