### ISSUE TITLE
Local time

### ISSUE THREAD

**Issue by Devqon** [davidrustingha/F1-Calendar-Card#4]
Hi, in your example I can see you're Dutch. How do you render the time in our local timezone? Can you share your specific Dutch configuration?

**Comment by iron-LAN** [comment]
I dont understand the question I think. 
As long as you add the calendar to your own Google account (in the correct timezone), and add it to HA (also in the correct timezone) it will render all events in the correct timezone. There is no specific timezone configuration needed inside the card or sensors created.
