### ISSUE TITLE
Template warning: 'timestamp_custom' got invalid input '0'

### ISSUE THREAD

**Issue by petersoniq** [davidrustingha/F1-Calendar-Card#6]
Logger: homeassistant.helpers.template
Source: helpers/template.py:1286
First occurred: 13:22:12 (51 occurrences)
Last logged: 13:23:00

Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{% if state_attr('calendar.f1_fp3', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_fp3', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) != (now().isocalendar()[1]) %} No 3rd free practice this week {% else %} {{ as_timestamp(state_attr('calendar.f1_fp3', 'start_time'), '0') | timestamp_custom('%A %d %B', '0') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{% if state_attr('calendar.f1_fp1', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_fp1', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) != (now().isocalendar()[1]) %} No 1st free practice this week {% else %} {{ as_timestamp(state_attr('calendar.f1_fp1', 'start_time'), '0') | timestamp_custom('%A %d %B', '0') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{{ as_timestamp(state_attr('calendar.f1_race', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) == (now().isocalendar()[1]) }}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{% if state_attr('calendar.f1_fp2', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_fp2', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) != (now().isocalendar()[1]) %} No 2nd free practice this week {% else %} {{ as_timestamp(state_attr('calendar.f1_fp2', 'start_time'), '0') | timestamp_custom('%H:%M', '0') }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'timestamp_custom' got invalid input '0' when rendering template '{% if state_attr('calendar.f1_fp2', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_fp2', 'start_time'), '0') | timestamp_custom('%W', '0') | float(0) != (now().isocalendar()[1]) %} No 2nd free practice this week {% else %} {{ as_timestamp(state_attr('calendar.f1_fp2', 'start_time'), '0') | timestamp_custom('%A %d %B', '0') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return '0', however this template will fail to render in Home Assistant core 2022.1

**Comment by iron-LAN** [comment]
Hi @petersoniq,

I'm aware of the issue. The problem is that I do not have the issue. When I get home I will update the code of the sensor to what I currently use, maybe there is something different in the code I'm using right now.

**Comment by petersoniq** [comment]
> 

Thank you.
I used your template without modifications with the latest version HA 2022.2.5

**Comment by iron-LAN** [comment]
Hi Peter,

I have checked and the template sensor i'm using is the exact same one as in the repo.

Im going to investigate this further, so for now sit tight. I hope it doesn't cause too much problems.

**Comment by iron-LAN** [comment]
I have uploaded a new version of the template sensor file. Could you try that and see if you get any errors?

**Comment by petersoniq** [comment]
Thank you  @davidrustingha . Works good.
As I understand your changes. You change **timestamp_custom('%H:%M', '0')** to **timestamp_custom('%H:%M', 0)**

**Comment by iron-LAN** [comment]
Exactly. These templates are a learning curve for me too haha.
What the issue was, I think, is that the template is looking for a date time object, and '0' is just 0 in a normal expression.
