### ISSUE TITLE
Request: Next race info

### ISSUE THREAD

**Issue by Alfagek** [davidrustingha/F1-Calendar-Card#7]
**Is your feature request related to a problem? Please describe.**
Maybe a nice thing is, to also let show the next upcoming racetrack and date. 
I'm waiting to the next race ;-) Its to long a go hahahhaahah

**Describe the solution you'd like**
In the card, showing in the bottom the next race that is coming (only date and track will be enough i think)

**Describe alternatives you've considered**

**Additional context**

**Comment by iron-LAN** [comment]
Hi,

Sadly it is not possible right now due to the calendar integration only showing the next upcoming event (in the current week).
I'm currently exploring other options to get the data, but I have yet to find a good solution.

**Comment by Alfagek** [comment]
Hey David,

Is it not possible to put in in the template. Your old template did show the next race (not this week). 

I switch this week finally to the new version, that’s why i missed the next race. In the old version it was showing next race: 18 maart

Not that I’m very good in programming ;-)

**Comment by iron-LAN** [comment]
Hey you're right. The info is available, I just have to find some time to implement it.
I'll reopen this for now, I'll get back to you!

**Comment by iron-LAN** [comment]
I have updated the card and also the sensor. You need to update them both for the new card to work.

**Comment by Alfagek** [comment]
Je bent een Topper 🥇 

Working great 😃 
![image](https://user-images.githubusercontent.com/76258622/154739641-e8b7d71e-a84a-454d-9678-6068e6327b1f.png)

**Comment by iron-LAN** [comment]
Awesome! Enjoy :)

**Comment by Alfagek** [comment]
Hey David @davidrustingha,

I did see you made a change with “week”(s) in the card. 

But this week we have a race, and my card is still showing the first card and not the race card (it’s finally race week 😁). 

And the time I see is UTC I think. For the practice 1 it’s saying 12:00. But it’s for you and me 13:00. And that’s about all the times this weekend. 

Thanks for looking in to it 🤛🏻

**Comment by iron-LAN** [comment]
Hi, I'm aware of the problem, I saw it this morning too.
I'm pretty busy at work this week, but I think I have some time tomorrow.

You should be notified as soon as I push updates to this repo.

**Comment by Alfagek** [comment]
No problem @davidrustingha  

Will keep a eye on it. Take your time. 
Thanks in advanced 🤛🏻

**Comment by iron-LAN** [comment]
@Alfagek found some time just now, fixed the card. Make sure to update both the card and template sensor for the changes to work :)

**Comment by Alfagek** [comment]
@davidrustingha , working like a charm 👍🏻

Thanks for the quick fix and time 🤛🏻

**Comment by Alfagek** [comment]
@davidrustingha , 

only we have to dive in the template error we have now in the log ;-)

**Comment by Alfagek** [comment]
`Template warning: 'timestamp_custom' got invalid input 'None' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%W') | float(0) != (now().isocalendar()[1]),0 %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return 'None', however this template will fail to render in Home Assistant core 2022.1

Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%W') | float(0) != (now().isocalendar()[1]) %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1

Template warning: 'timestamp_custom' got invalid input 'None' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%W') | float(0) != (now().isocalendar()[1]) %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%A %d %B') | replace("Monday", "maandag") | replace("Tuesday", "dinsdag") | replace("Wednesday", "woensdag") | replace("Thursday", "donderdag") | replace("Friday", "vrijdag") | replace("Saturday", "zaterdag") | replace("Sunday", "zondag") | replace("January", "januari") | replace("February", "februari") | replace("March", "maart") | replace("April", "april") | replace("May", "mei") | replace("June", "juni") | replace("July", "juli") | replace("August", "augustus") | replace("September", "september") | replace("October", "oktober") | replace("November", "november") | replace("December", "december") }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return 'None', however this template will fail to render in Home Assistant core 2022.1
Template warning: 'as_timestamp' got invalid input 'None' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%W') | float(0) != (now().isocalendar()[1]) %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'as_timestamp' will return 'None', however this template will fail to render in Home Assistant core 2022.1

Template warning: 'timestamp_custom' got invalid input 'None' when rendering template '{% if state_attr('calendar.f1_sprint_qualifying', 'start_time') == 'None' or as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%W') | float(0) != (now().isocalendar()[1]) %} No sprint qualification this week {% else %} {{ as_timestamp(state_attr('calendar.f1_sprint_qualifying', 'start_time')) | timestamp_custom('%H:%M') }} {% endif %}' but no default was specified. Currently 'timestamp_custom' will return 'None', however this template will fail to render in Home Assistant core 2022.1`

can't getting my finger on it to remove the error in the logs
